import type { Locale } from '../../i18n';

export const SEO_LOCALES: readonly Locale[] = ['ca', 'es', 'en', 'fr'];
export const SEO_SITE = 'https://eclipsi.info/';

export function prefix(locale: Locale): string { return locale === 'ca' ? '' : `${locale}/`; }

const TEXT = {
  ca: { eclipse:'Eclipsi', city:'Eclipsi a', point:'Punt oficial', home:'Inici', cities:'Ciutats', points:'Punts oficials', guides:'Guies pràctiques', conjunction:'i', calculate:'Calcula-ho al punt exacte', source:'Font oficial', coords:'Coordenades', elevation:'Altitud publicada', climatology:'Climatologia local', skyScore:'Índex històric de cel favorable', clearYears:'Mostres amb cel favorable', cloudyYears:'Mostres amb cel molt tapat', climCaveat:'És climatologia històrica d’Open-Meteo, NO una previsió del dia de l’eclipsi.', central:'fase central', partial:'eclipsi parcial', maximum:'Màxim', duration:'Durada de la fase central', obscuration:'Disc solar tapat', sun:'Altura del Sol al màxim', noCentral:'Sense fase central en aquest punt', related:'També et pot interessar', intro:'Horaris i visibilitat calculats per a aquest punt amb el motor topocèntric d’eclipsi.info.', disclaimer:'El relleu, els edificis i els núvols poden canviar el que veuràs. Obre el simulador per calcular l’horitzó real.', official:'Aquest emplaçament consta al catàleg publicat per l’administració indicada.', estimated:'La font publica el lloc però no una coordenada exacta; la posició del mapa és estimada.', exact:'Coordenada publicada per la font.', event:'Activitat amb entrada o reserva segons la convocatòria original.', observatory:'Observatori o planetari amb activitat anunciada.', openSite:'Punt d’observació oficial d’accés lliure segons la font.' },
  es: { eclipse:'Eclipse', city:'Eclipse en', point:'Punto oficial', home:'Inicio', cities:'Ciudades', points:'Puntos oficiales', guides:'Guías prácticas', conjunction:'y', calculate:'Calcúlalo en el punto exacto', source:'Fuente oficial', coords:'Coordenadas', elevation:'Altitud publicada', climatology:'Climatología local', skyScore:'Índice histórico de cielo favorable', clearYears:'Muestras con cielo favorable', cloudyYears:'Muestras con cielo muy cubierto', climCaveat:'Es climatología histórica de Open-Meteo, NO una previsión para el día del eclipse.', central:'fase central', partial:'eclipse parcial', maximum:'Máximo', duration:'Duración de la fase central', obscuration:'Disco solar cubierto', sun:'Altura del Sol en el máximo', noCentral:'Sin fase central en este punto', related:'También te puede interesar', intro:'Horarios y visibilidad calculados para este punto con el motor topocéntrico de eclipsi.info.', disclaimer:'El relieve, los edificios y las nubes pueden cambiar lo que verás. Abre el simulador para calcular el horizonte real.', official:'Este emplazamiento figura en el catálogo publicado por la administración indicada.', estimated:'La fuente publica el lugar, pero no una coordenada exacta; la posición del mapa es estimada.', exact:'Coordenada publicada por la fuente.', event:'Actividad con entrada o reserva según la convocatoria original.', observatory:'Observatorio o planetario con actividad anunciada.', openSite:'Punto oficial de observación de acceso libre según la fuente.' },
  en: { eclipse:'Eclipse', city:'Eclipse in', point:'Official viewing site', home:'Home', cities:'Cities', points:'Official sites', guides:'Practical guides', conjunction:'and', calculate:'Calculate your exact point', source:'Official source', coords:'Coordinates', elevation:'Published elevation', climatology:'Local climatology', skyScore:'Historical favourable-sky score', clearYears:'Samples with favourable sky', cloudyYears:'Samples with heavy cloud', climCaveat:'This is historical Open-Meteo climatology, NOT a forecast for eclipse day.', central:'central phase', partial:'partial eclipse', maximum:'Maximum', duration:'Central phase duration', obscuration:'Solar disc covered', sun:'Sun altitude at maximum', noCentral:'No central phase at this point', related:'Related pages', intro:'Times and visibility calculated for this point with eclipsi.info’s topocentric engine.', disclaimer:'Terrain, buildings and clouds can change what you see. Open the simulator to calculate the real horizon.', official:'This location appears in the catalogue published by the named public authority.', estimated:'The source names the place but gives no exact coordinates; its map position is estimated.', exact:'Coordinates published by the source.', event:'Ticket or reservation required according to the original announcement.', observatory:'Observatory or planetarium with an announced activity.', openSite:'Official free-access viewing site according to the source.' },
  fr: { eclipse:'Éclipse', city:'Éclipse à', point:'Site officiel', home:'Accueil', cities:'Villes', points:'Sites officiels', guides:'Guides pratiques', conjunction:'et', calculate:'Calculer votre point exact', source:'Source officielle', coords:'Coordonnées', elevation:'Altitude publiée', climatology:'Climatologie locale', skyScore:'Indice historique de ciel favorable', clearYears:'Échantillons avec ciel favorable', cloudyYears:'Échantillons avec ciel très couvert', climCaveat:'Il s’agit de climatologie historique Open-Meteo, PAS d’une prévision pour le jour de l’éclipse.', central:'phase centrale', partial:'éclipse partielle', maximum:'Maximum', duration:'Durée de la phase centrale', obscuration:'Disque solaire couvert', sun:'Hauteur du Soleil au maximum', noCentral:'Aucune phase centrale en ce point', related:'À voir aussi', intro:'Horaires et visibilité calculés pour ce point avec le moteur topocentrique d’eclipsi.info.', disclaimer:'Le relief, les bâtiments et les nuages peuvent modifier ce que vous verrez. Ouvrez le simulateur pour calculer l’horizon réel.', official:'Ce site figure dans le catalogue publié par l’autorité indiquée.', estimated:'La source nomme le lieu sans fournir de coordonnées exactes ; sa position sur la carte est estimée.', exact:'Coordonnées publiées par la source.', event:'Billet ou réservation requis selon l’annonce originale.', observatory:'Observatoire ou planétarium avec activité annoncée.', openSite:'Site officiel d’observation en accès libre selon la source.' },
} as const;

export function seoStrings(locale: Locale) { return TEXT[locale]; }
